#!/bin/sh

set -eu

PROFILE_FILE="/etc/n60pro-profile.conf"
SQM_TIER="${SQM_TIER:-300m}"

if [ -f "${PROFILE_FILE}" ]; then
	# shellcheck disable=SC1090
	. "${PROFILE_FILE}"
fi

SQM_TIER="${SQM_TIER:-300m}"
[ "${SQM_TIER}" = "none" ] && exit 0

if ! command -v uci >/dev/null 2>&1; then
	exit 0
fi

if [ ! -f /etc/config/sqm ]; then
	touch /etc/config/sqm
fi

SQM_IFACE="${SQM_IFACE:-pppoe-wan}"
SQM_QDISC="${SQM_QDISC:-cake}"
SQM_SCRIPT="${SQM_SCRIPT:-layer_cake.qos}"
SQM_LINKLAYER="${SQM_LINKLAYER:-ethernet}"
SQM_OVERHEAD="${SQM_OVERHEAD:-44}"

case "${SQM_TIER}" in
100m)
	DL_KBIT="${SQM_DOWNLOAD:-95000}"
	UL_KBIT="${SQM_UPLOAD:-30000}"
	;;
300m)
	DL_KBIT="${SQM_DOWNLOAD:-285000}"
	UL_KBIT="${SQM_UPLOAD:-80000}"
	;;
1g)
	DL_KBIT="${SQM_DOWNLOAD:-850000}"
	UL_KBIT="${SQM_UPLOAD:-100000}"
	;;
*)
	DL_KBIT="${SQM_DOWNLOAD:-285000}"
	UL_KBIT="${SQM_UPLOAD:-80000}"
	;;
esac

# 若尚未初始化 queue，则创建默认 section；已存在则只做幂等覆盖。
if ! uci -q show sqm | grep -q "=queue"; then
	uci -q add sqm queue >/dev/null
fi

uci -q set sqm.@queue[0].enabled='1'
uci -q set sqm.@queue[0].interface="${SQM_IFACE}"
uci -q set sqm.@queue[0].download="${DL_KBIT}"
uci -q set sqm.@queue[0].upload="${UL_KBIT}"
uci -q set sqm.@queue[0].qdisc="${SQM_QDISC}"
uci -q set sqm.@queue[0].script="${SQM_SCRIPT}"
uci -q set sqm.@queue[0].linklayer="${SQM_LINKLAYER}"
uci -q set sqm.@queue[0].overhead="${SQM_OVERHEAD}"
uci -q set sqm.@queue[0].qdisc_advanced='0'
uci -q set sqm.@queue[0].verbosity='5'
uci -q set sqm.@queue[0].debug_logging='0'
uci -q set sqm.@queue[0].squash_dscp='0'
uci -q set sqm.@queue[0].squash_ingress='0'
uci -q set sqm.@queue[0].ingress_ecn='ECN'
uci -q set sqm.@queue[0].egress_ecn='ECN'

uci -q commit sqm || true

exit 0
